server:
  port: 8091
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: admin
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sriram
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
